### ISSUE TITLE
Background image opinions

### ISSUE THREAD

**Issue by Arnold-Og** [LancemDev/TransitTrack#11]
I need you to tell me if you like the image I used for the background. Also, go to the code and on the play around with bg-img then tell me if you prefer the background-size to be cover or contain, while also confirming the readability of the text in that section.

Cover
![image](https://github.com/LancemDev/TransitTrack/assets/127428952/5a3039c3-bb89-4108-9585-b30decc7bcbb)

Contain
![image](https://github.com/LancemDev/TransitTrack/assets/127428952/b77c923d-55e1-47a0-928d-f2e53595e6f7)

**Comment by LancemDev** [comment]
I like the image used. The text at efficient is not clearly visible. The rest is visible though.

The rest of the homepage is actually really well done. 😅 

Get Started on hover is a bit blinding. If you could change the text to another color on hover


![image](https://github.com/LancemDev/TransitTrack/assets/74910038/fe480e8e-6eed-4cea-9d42-cad72320b73b)
The navigation bar seems a bit longer that a normal one, if you could correct that.

**Comment by LancemDev** [comment]
convenient is mispelled as well

**Comment by Arnold-Og** [comment]
Aight, noted. Thanks for feedback.
