### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by LancemDev** [LancemDev/TransitTrack#12]
If you'd like to modify the existing theme you can do so from the app layout blade file.

Documentation is on the official daisyui website:  https://daisyui.com/docs/themes/

![image](https://github.com/LancemDev/TransitTrack/assets/74910038/d2501d8f-78cc-4a64-bdcb-b319823a12fc)

**Comment by Arnold-Og** [comment]
Where is the file that i am supposed to change the theme in?

**Comment by Arnold-Og** [comment]
Nevermind i found it, I decided to go with bumblebee since it matches with the home page. Have you linked the login and registration with the needed users?

**Comment by LancemDev** [comment]
Bumblebee is nice.
I removed the Auth logic but I'm working on it now. It's taken long because I'm using a method I've never used before
